import Head from "next/head";
import Layout from "./Layout";
import style from "../styles/home.module.scss";

export default function Home() {
    return (
        <Layout>
            <Head>
                <title>Blog post</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={`${style.hero} `}>
                <div className={`${style.hero__container}  ${style.container}`}>
                    <div className={`${style["hero__heading-container"]}`}>
                        <h1>Expand your horizons</h1>
                        <p>Where curiosity meets insight and every word inspires new ideas and learnings</p>
                    </div>
                </div>
            </section>
        </Layout>
    );
}

